# -*- coding: utf-8 -*-
"""port

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pyo3ZRngc_tw2rD7Ao3chtvm6NVOQTEw
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np

st.title('Portfolio of Charu')